name: Deploy for preview

on:
  repository_dispatch:
    types: [deploy-command]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.github_token }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            ðŸš€ Pull-request application deployment starting.
          repo-token: ${{ secrets.github_token }}
          allow-repeats: true
          repo-token-user-login: 'github-actions[bot]'
  preview:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [12.16.2]

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.github_token }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Electron Builder Action
        uses: samuelmeuli/action-electron-builder@v1.2.0
        with:
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          github_token: ${{ secrets.github_token }}

      - name: Deploy S3 Website
        uses: blaadje/s3-website-pr-action@master
        with:
          bucket-prefix: 'blaadje-todo-list-app'
          folder-to-copy: 'build'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.github_token }}
